home/urls.py
from django.urls import path,re_path
from .views import SignUpView
from home import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url

urlpatterns = [
re_path(r'^$',views.base,name='base'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('visitorsform/',views.visitors, name="visitors"),
    path('quotation/',views.quotation_upload,name="quotation_upload"),
    #path('test/',views.test, name="test"),

    #path('password_reset/',auth_views.password_reset, name='password_reset'),
    #path('password_reset/done/', auth_views.password_reset_done, name='password_reset_done'),
    #re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        #auth_views.password_reset_confirm, name='password_reset_confirm'),
    #path('reset/done/', auth_views.password_reset_complete, name='password_reset_complete'),

   ]

society_website/urls.py
from django.contrib import admin
from django.urls import path, include 
from home import views,urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('member/',include('member.urls')),

    path('',views.test,name="test"),
    path('home/',include('home.urls')),
    path('home/', include('django.contrib.auth.urls')),
    path('commitee/',include('commitee.urls')),
    path('member/', views.login_success, name='login_success'),

    path('login/', views.login_success, name='login_success'),
     

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class visitors(models.Model):
	name=models.CharField(max_length=50)
	telephone=models.CharField(max_length=10,primary_key=True)
	flat_no=models.CharField(max_length=10)
	purpose=models.CharField(max_length=50)

class CustomUser(AbstractUser):

	# add additional fields in here
	name=models.CharField(max_length=256)
	username=models.CharField(max_length=100,primary_key=True)
	password=models.CharField(max_length=100)
	telephone=models.CharField(max_length=10)
	flat_no = models.CharField(max_length=20)
	email = models.EmailField(max_length=100)

	rights = models.CharField(max_length=10, default="normal")


class Quotation(models.Model):
	company_name=models.CharField(max_length=50)
	telephone=models.CharField(max_length=10)
	email=models.CharField(max_length=20)
	description=models.CharField(max_length=100)
	pdf=models.FileField(upload_to='quotations/pdfs/')


def __str__(self):
	return self.name

home/forms.py
from django.forms import ModelForm
from home.models import visitors,Quotation
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser 
from django import forms 

class visitorsform(ModelForm):
	wing_choices = [
	('A', 'A'),
	('B', 'B'),
	('C', 'C'),

	]
	wing=forms.CharField(max_length=1, widget=forms.Select(choices=wing_choices),)

	flat_choices=[
	('101','101'),
	('102','102'),
	('103','103'),
	('104','104'),
	('201','201'),
	('202','202'),
	('203','203'),
	('204','204'),
	('301','301'),
	('302','302'),
	('303','303'),
	('304','304'),
	('401','401'),
	('402','402'),
	('403','403'),
	('404','404'),
	('501','501'),
	('502','502'),
	('503','503'),
	('504','504'),
	('601','601'),
	('602','602'),
	('603','603'),
	('604','604'),
	('701','701'),
	('702','702'),
	('703','703'),
	('704','704'),
	('801','801'),
	('802','802'),
	('803','803'),
	('804','804'),
	('901','901'),
	('902','902'),
	('903','903'),
	('904','904'),

	]
	flat=forms.CharField(max_length=3,
	widget=forms.Select(choices=flat_choices),)
	class Meta:
		model=visitors
		fields=('name','telephone','flat_no','purpose')
		exclude=['flat_no']


class CustomUserCreationForm(UserCreationForm):
	wing_choices = [
	('A', 'A'),
	('B', 'B'),
	('C', 'C'),

	]
	wing=forms.CharField(max_length=1, widget=forms.Select(choices=wing_choices),)

	flat_choices=[
	('101','101'),
	('102','102'),
	('103','103'),
	('104','104'),
	('201','201'),
	('202','202'),
	('203','203'),
	('204','204'),
	('301','301'),
	('302','302'),
	('303','303'),
	('304','304'),
	('401','401'),
	('402','402'),
	('403','403'),
	('404','404'),
	('501','501'),
	('502','502'),
	('503','503'),
	('504','504'),
	('601','601'),
	('602','602'),
	('603','603'),
	('604','604'),
	('701','701'),
	('702','702'),
	('703','703'),
	('704','704'),
	('801','801'),
	('802','802'),
	('803','803'),
	('804','804'),
	('901','901'),
	('902','902'),
	('903','903'),
	('904','904'),

	]
	flat=forms.CharField(max_length=3,
	widget=forms.Select(choices=flat_choices),)
	rights=forms.CharField(max_length=10 ,widget = forms.HiddenInput(),required=False)
		
	#rights = forms.CharField(widget=forms.HiddenInput(),initial="normal")
	class Meta(UserCreationForm):
		model = CustomUser
		fields=('name','username','telephone','flat_no','email')
		exclude=['flat_no']


class CustomUserChangeForm(UserChangeForm):

	wing_choices = [
	('A', 'A'),
	('B', 'B'),
	('C', 'C'),

	]
	wing=forms.CharField(max_length=1, widget=forms.Select(choices=wing_choices),)

	flat_choices=[
	('101','101'),
	('102','102'),
	('103','103'),
	('104','104'),
	('201','201'),
	('202','202'),
	('203','203'),
	('204','204'),
	('301','301'),
	('302','302'),
	('303','303'),
	('304','304'),
	('401','401'),
	('402','402'),
	('403','403'),
	('404','404'),
	('501','501'),
	('502','502'),
	('503','503'),
	('504','504'),
	('601','601'),
	('602','602'),
	('603','603'),
	('604','604'),
	('701','701'),
	('702','702'),
	('703','703'),
	('704','704'),
	('801','801'),
	('802','802'),
	('803','803'),
	('804','804'),
	('901','901'),
	('902','902'),
	('903','903'),
	('904','904'),

	]
	flat=forms.CharField(max_length=3,
	widget=forms.Select(choices=flat_choices),
	)
	rights=forms.CharField(max_length=10 ,widget = forms.HiddenInput(),required=False)
	class Meta(UserChangeForm):
		model = CustomUser
		fields = ('name','username','telephone','flat_no','email')
		exclude=['flat_no','rights']



class quotationform(ModelForm):
	
	class Meta:
		model=Quotation
		fields='__all__'

home/views.py
from home.models import visitors,CustomUser
from django.shortcuts import render
# Create your views here.
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from home import forms
from .forms import CustomUserCreationForm,quotationform
from django.views.generic import View
from django.shortcuts import redirect
from commitee.models import announcement

def home(request):
	return render(request,"home/homepage.html")

def base(request):
	
	return render(request,"registration/base.html")


def visitors(request):
	if request.method == 'POST':
		form=forms.visitorsform(request.POST)
		if form.is_valid():
			s = form.cleaned_data['wing']
			t=form.cleaned_data['flat']
			st=s+t
			record=form.save(commit=False)
			record.flat_no=st
			record=form.save()
			record.save()
			form=forms.visitorsform()
	else:
		form=forms.visitorsform()
	return render(request, "home/visitors.html",{'form':form})
	
class SignUpView(CreateView):
	form_class = CustomUserCreationForm
	success_url = reverse_lazy('login')
	template_name = 'home/signup.html'

	def form_valid(self,form_class):
		s=form_class.cleaned_data['wing']
		t=form_class.cleaned_data['flat']
		st=s+t
		form_class.instance.flat_no=st
		return super().form_valid(form_class)

def quotation_upload(request):
	if request.method == 'POST':
		form=forms.quotationform(request.POST,request.FILES)
		if form.is_valid():
			record=form.save()
			record.save()
			form=forms.quotationform()

	else:
		form=forms.quotationform()
	return render(request, "home/quotation.html",{'form':form})

def login_success(request):
	rights=request.user.rights
	if rights== "commitee":
		return redirect("/commitee/option")
	elif rights == "Admin" :
		return redirect("/commitee/admin")
	else:
		return redirect("/member/complaint")


def test(request):

	a=announcement.objects.all()

	return render(request,"home/test.html",{'a':a})

templates/home/quotation.html
{% load static %}
{% load bootstrap4 %}

<head>
	<title>Quotation</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static 'form/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'form/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'form/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'form/fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'form/vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'form/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'form/vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'form/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'form/vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'form/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'form/css/main.css' %}">
<!--===============================================================================================-->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
	<br>
<div class="wrap-contact100" style="margin-left: 25%;">
			<div class="contact100-form-title" style="background-image: url({% static 'form/images/bg-01.jpg' %});">
				<span class="contact100-form-title-1">
					Quotation
				</span>

				<span class="contact100-form-title-2">
					Enter the details Below!
				</span>
			</div>
	<form  method="post" class="contact100-form " enctype="multipart/form-data" >
		{% csrf_token %}

				<div class="wrap-input100 ">
					{% if form.company_name.errors %}
						<ul class="errorlist">
    						<li style="font-size: 10px;color: red;font-style: italic;">Company Name is required.</li>
						</ul>
					{% endif %}

					<span class="label-input100">Company Name</span>
					<input type="text" name="company_name" required maxlength="50" id="id_company_name" class="input100" placeholder="Company Name">
					<span class="focus-input100"></span>
				</div>


				<div class="wrap-input100 ">
					{% if form.telephone.errors %}
						<ul class="errorlist">
    						<li style="font-size: 10px;color: red;font-style: italic;">Telephone field is required.</li>
						</ul>
					{% endif %}

					<span class="label-input100">Telephone:</span>
					<input class="input100" id="id_telephone" type="text" name="telephone" placeholder="Telephone">
					<span class="focus-input100"></span>
				</div>


				<div class="wrap-input100 ">
					{% if form.email.errors %}
						<ul class="errorlist">
    						<li style="font-size: 10px;color: red;font-style: italic;">Email field is required.</li>
						</ul>
					{% endif %}

					<span class="label-input100">Email:</span>
					
					<input class="input100" id="id_email" type="text" name="email" placeholder="Email">
					<span class="focus-input100"></span>
				</div>

				<div class="wrap-input100 ">
					{% if form.description.errors %}
						<ul class="errorlist">
    						<li style="font-size: 10px;color: red;font-style: italic;">Description is required.</li>
						</ul>
					{% endif %}

					<span class="label-input100">Description:</span>
					<textarea class="input100" id="id_description" name="description" placeholder="Enter Description"></textarea>
					<span class="focus-input100"></span>
				</div>

				<div class="wrap-drop100 ">

					{% if form.pdf.errors %}
						<ul class="errorlist">
    						<li style="font-size: 10px;color: red;font-style: italic;">This Field is required.</li>
						</ul>
					{% endif %}

					<span idclass="label-input100">Documents:</span>
					{{form.pdf}}
				</div>

				<div class="container-contact100-form-btn">
				<input type="submit" class="contact100-form-btn" value="Submit"  style="margin-left: 80px;"/>
				</div>

		
	</form>
</div>
</body>


<a href="/" class="btn btn-danger" style="float: right; font-size:15px; vertical-align:middle; margin-bottom: 10px; margin-right: 10px;"> Back</a>

templates/home/signup.html
{% load static %}
<html lang="en">
<head>
	<title>Sign Up </title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100"  style="background-image:linear-gradient(
      rgba(0, 0, 0, 0.65), 
     rgba(0, 0, 0, 0.65)
    ), url({% static 'images/bg-01.jpg' %});background-size: cover;z-index: 1" >

			<div class="wrap-login100" style="padding-top: 10px; padding-left: 40px;">
				<div class="login100-pic js-tilt" data-tilt >
					<img src="{% static 'images/img-01.png' %}" alt="IMG" style="padding-top:50%;">
				</div>
			<div style="padding-right: 10%;">
				<form  method="POST" style="padding-right:10%;width: 140%;">
					{% csrf_token %}<br>
					<span class="login100-form-title">
						Sign Up 
					</span>

					<div  class="wrap-input100 " style="width: 290px;">
						{% if form.non_field_errors %}
						<ul>
					    {% for error in form.non_field_errors %}
					        <li style="font-size: 10px;color: red;font-style: italic;">{{ error|escape }}</li>
					    {% endfor %}
					    </ul>
						{% endif %}
					</div>
					<!--<div><h6>{{ form.non_field_errors }}</h6></div>-->
					<div class="wrap-input100 " >
					{% if form.name.errors %}
						<ul class="errorlist">
    						<li style="font-size: 10px;color: red;font-style: italic;">Name is required.</li>
						</ul>
					{% endif %}
						<input id="id_name" class="input100" type="text" name="name" placeholder="Name" style="padding-left: 5%">
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 " >
					{% if form.wing.errors %}
						<ul class="errorlist">
    						<li style="font-size: 10px;color: red;font-style: italic;">Wing Field is required.</li>
						</ul>
					{% endif %}
					{% if form.flat.errors %}
						<ul class="errorlist">
    						<li style="font-size: 10px;color: red;font-style: italic;">Flat No Field is required.</li>
						</ul>
					{% endif %}
					<div style="display: flex;flex-direction: row;">
					<select name="wing" maxlength="1" id="id_wing" class="input100"  style="width:35%;padding-left: 5%;padding-right: 5%;border: hidden;">
						<option value="" disabled selected>Wing</option>
						<option value="A">A</option>

						<option value="B">B</option>

						<option value="C">C</option>

					</select>&nbsp
					<span class="focus-input100"></span>

					<select name="flat" maxlength="3" id="id_flat" class="input100"  style="width:55%;padding-left: 5%;padding-right: 5%;border: hidden;">
					<option value="" disabled selected>Flat No</option>	
					<option value="101">101</option>

					<option value="102">102</option>

					<option value="103">103</option>

					<option value="104">104</option>

					<option value="201">201</option>

					<option value="202">202</option>

					<option value="203">203</option>

					<option value="204">204</option>

					<option value="301">301</option>

					<option value="302">302</option>

					<option value="303">303</option>

					<option value="304">304</option>

					<option value="401">401</option>

					<option value="402">402</option>

					<option value="403">403</option>

					<option value="404">404</option>

					<option value="501">501</option>

					<option value="502">502</option>

					<option value="503">503</option>

					<option value="504">504</option>

					<option value="601">601</option>

					<option value="602">602</option>

					<option value="603">603</option>

					<option value="604">604</option>

					<option value="701">701</option>

					<option value="702">702</option>

					<option value="703">703</option>

					<option value="704">704</option>

					<option value="801">801</option>

					<option value="802">802</option>

					<option value="803">803</option>

					<option value="804">804</option>

					<option value="901">901</option>

					<option value="902">902</option>

					<option value="903">903</option>

					<option value="904">904</option>

					</select>
					<span class="focus-input100"></span>
				</div>
					</div>

					<div class="wrap-input100 " >
					{% if form.username.errors %}
					    <ul>
					    {% for error in form.username.errors %}
					        <li style="font-size: 10px;color: red;font-style: italic;">{{ error|escape }}</li>
					    {% endfor %}
					    </ul>
					{% endif %}
						<input id="id_username" class="input100" type="text" name="username" placeholder="Username" style="padding-left: 5%">
						<span class="focus-input100"></span>
						
					</div>

					<div class="wrap-input100 " >
					{% if form.email.errors %}
					    <ul>
					    {% for error in form.email.errors %}
					        <li style="font-size: 10px;color: red;font-style: italic;">{{ error|escape }}</li>
					    {% endfor %}
					    </ul>
					{% endif %}
						<input id="id_email" class="input100" type="email" name="email" placeholder="Email" style="padding-left: 5%">
						<span class="focus-input100"></span>
						
					</div>

					<div class="wrap-input100 " >
					{% if form.telephone.errors %}
					    <ul>
					    {% for error in form.telephone.errors %}
					        <li style="font-size: 10px;color: red;font-style: italic;">{{ error|escape }}</li>
					    {% endfor %}
					    </ul>
					{% endif %}
						<input id="id_telephone" class="input100" type="text" name="telephone" placeholder="Mobile No" style="padding-left: 5%">
						<span class="focus-input100"></span>
						
					</div>



					<div class="wrap-input100 " >
					{% if form.password1.errors %}
					    <ul>
					    {% for error in form.password.errors %}
					        <li style="font-size: 10px;color: red;font-style: italic;">{{ error|escape }}</li>
					    {% endfor %}
					    </ul>
					{% endif %}
				
						<input id="id_password1" class="input100" type="password" name="password1" placeholder="Password" style="padding-left: 5%">
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 " >
					{% if form.password2.errors %}
					    <ul>
					    {% for error in form.password2.errors %}
					        <li style="font-size: 10px;color: red;font-style: italic;">{{ error|escape }}</li>
					    {% endfor %}
					    </ul>
					{% endif %}
				
						<input id="id_password2" class="input100" type="password" name="password2" placeholder=" Confirm Password" style="padding-left: 5%">
						<span class="focus-input100"></span>
					</div>



					<div class="container-login100-form-btn">
						<button class="login100-form-btn" type="submit">
							Sign Up 
						</button>
					</div>

					

					<div class="text-center p-t-35">
						<a class="txt2" href="{% url 'login' %}">
							Already have an Account? Login
							<i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
						</a>
					</div>


					<div class="text-center p-t-12">
						<a class="txt2" href=/><h5 style="color: red">Back</h5>
						<i class="fa fa-long-arrow-left m-l-10" aria-hidden="true"></i>
						</a>
					</div>
				</form>
				</div>
			</div>
		</div>
	</div>
	
	

	
<!--===============================================================================================-->	
	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/tilt/tilt.jquery.min.js' %}"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
<!--===============================================================================================-->
	<script src="{% static 'js/main1.js' %}"></script>

</body>
</html>

templates/home/visitors.html
{% load static %}
<head>
	<title>Visitor</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static 'form/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'form/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'form/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'form/fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'form/vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'form/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'form/vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'form/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'form/vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'form/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'form/css/main.css' %}">
<!--===============================================================================================-->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
	<br>
<div class="wrap-contact100" style="margin-left: 25%;">
			<div class="contact100-form-title" style="background-image: url({% static 'form/images/bg-01.jpg' %});">
				<span class="contact100-form-title-1">
					Visitor
				</span>

				<span class="contact100-form-title-2">
					Enter the details Below!
				</span>
			</div>
	<form  method="post" class="contact100-form " >
		{% csrf_token %}

	
				<div class="wrap-drop100 ">
					{% if form.wing.errors %}
						<ul class="errorlist">
    						<li style="font-size: 10px;color: red;font-style: italic;">Wing is required.</li>
						</ul>
					{% endif %}

					<span class="label-input100">Wing:</span>

					<select name="wing" maxlength="1" id="id_wing" class="drop100">
  					<option value="A">A</option>
  					<option value="B">B</option>
  					<option value="C">C</option>
					</select>
				</div>

				<div class="wrap-drop100 ">
					{% if form.flat.errors %}
						<ul class="errorlist">
    						<li style="font-size: 10px;color: red;font-style: italic;">Flat no. is required.</li>
						</ul>
					{% endif %}

					<span class="label-input100">Flat no:</span>
					<select name="flat" maxlength="3" id="id_flat" class="drop100">
  <option value="101">101</option>

  <option value="102">102</option>

  <option value="103">103</option>

  <option value="104">104</option>

  <option value="201">201</option>

  <option value="202">202</option>

  <option value="203">203</option>

  <option value="204">204</option>

  <option value="301">301</option>

  <option value="302">302</option>

  <option value="303">303</option>

  <option value="304">304</option>

  <option value="401">401</option>

  <option value="402">402</option>

  <option value="403">403</option>

  <option value="404">404</option>

  <option value="501">501</option>

  <option value="502">502</option>

  <option value="503">503</option>

  <option value="504">504</option>

  <option value="601">601</option>

  <option value="602">602</option>

  <option value="603">603</option>

  <option value="604">604</option>

  <option value="701">701</option>

  <option value="702">702</option>

  <option value="703">703</option>

  <option value="704">704</option>

  <option value="801">801</option>

  <option value="802">802</option>

  <option value="803">803</option>

  <option value="804">804</option>

  <option value="901">901</option>

  <option value="902">902</option>

  <option value="903">903</option>

  <option value="904">904</option>

</select>
				</div>

				<div class="wrap-input100 ">
					{% if form.name.errors %}
						<ul class="errorlist">
    						<li style="font-size: 10px;color: red;font-style: italic;">Name is required.</li>
						</ul>
					{% endif %}

					<span class="label-input100">Name:</span>
					<input type="text" name="name" required maxlength="50" id="id_name" class="input100">
					<span class="focus-input100"></span>
				</div>

				<div class="wrap-input100 ">
					{% if form.telephone.errors %}
						<ul class="errorlist">
    						<li style="font-size: 10px;color: red;font-style: italic;">Telephone is required.</li>
						</ul>
					{% endif %}

					<span class="label-input100">Telephone:</span>
					<input type="text" name="telephone" required maxlength="10" id="id_telephone" class="input100">
					<span class="focus-input100"></span>
				</div>


				<div class="wrap-input100 ">
					{% if form.purpose.errors %}
						<ul class="errorlist">
    						<li style="font-size: 10px;color: red;font-style: italic;">Purpose is required.</li>
						</ul>
					{% endif %}

					<span class="label-input100">Purpose:</span>
					<input type="text" name="purpose" required maxlength="50" id="id_purpose" class="input100">
					<span class="focus-input100"></span>
				</div>

	<div class="container-contact100-form-btn">
				<input type="submit" class="contact100-form-btn" value="Submit"  style="margin-left: 80px;"/>
				</div>




</form>
</div>

</body>
<a href="/" class="btn btn-danger" style="float: right; font-size:15px; vertical-align:middle; margin-bottom: 10px; margin-right: 10px"> Back</a>

</html>