home/urls.py
from django.urls import path,re_path
from .views import SignUpView
from home import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url

urlpatterns = [
re_path(r'^$',views.base,name='base'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('visitorsform/',views.visitors, name="visitors"),
    path('quotation/',views.quotation_upload,name="quotation_upload"),
    #path('test/',views.test, name="test"),

    #path('password_reset/',auth_views.password_reset, name='password_reset'),
    #path('password_reset/done/', auth_views.password_reset_done, name='password_reset_done'),
    #re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        #auth_views.password_reset_confirm, name='password_reset_confirm'),
    #path('reset/done/', auth_views.password_reset_complete, name='password_reset_complete'),

   ]

member/urls.py
from django.contrib import admin
from django.urls import path, re_path
from member import views
app_name='member'
urlpatterns = [
	re_path(r'^$',views.index,name='index'),
	path('complaint',views.complaint,name='complaint'),
	path('request',views.request,name='request'),
	path('cheque_details',views.cheque_details,name='cheque_details'),
	path('landl',views.landl,name='landl'),
	path('complaint_delete/<int:i>/',views.complaint_delete,name='complaint_delete'),

]

society_website/urls.py
from django.contrib import admin
from django.urls import path, include 
from home import views,urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('member/',include('member.urls')),

    path('',views.test,name="test"),
    path('home/',include('home.urls')),
    path('home/', include('django.contrib.auth.urls')),
    path('commitee/',include('commitee.urls')),
    path('member/', views.login_success, name='login_success'),

    path('login/', views.login_success, name='login_success'),
     

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

member/models.py
from django.db import models
from datetime import date
from django.utils import timezone
from django.core.validators import RegexValidator,MinValueValidator

#from home.models import CustomUser

# Create your models here.
class Complaint(models.Model):

        complaint_date=models.DateField( auto_now_add=True)
        flatno=models.CharField(max_length=5)
        username=models.CharField(max_length=200)
        #username= models.ForeignKey(CustomUser, on_delete=models.CASCADE)
        complaint_choices = [
        ('Intercom', 'Intercom'),
        ('Leakage', 'Leakage'),
        ('Cleaning', 'Cleaning'),
        ('Other','Other')
        ]
        complaint_type=models.CharField(
        max_length=100,
        choices=complaint_choices,
        default='Other',
        )
        description=models.CharField(max_length=500)
        complain_img = models.ImageField(upload_to='complaint_images/',null=True,blank=True) 



class Request(models.Model):

        
        request_date=models.DateField(auto_now_add=True)
        flatno=models.CharField(max_length=5)
        username=models.CharField(max_length=200)
        #username= models.ForeignKey(CustomUser, on_delete=models.CASCADE)
        request_choices = [
        ('NOC', 'NOC'),
        ('AddressProof', 'AddressProof(Passport)'),
        ('SalesAgreement', 'SalesAgreement(NOC)'),
        ('CCTV', 'CCTV'),
        ('Other','Other')
        ]
        request_type=models.CharField(max_length=100,choices=request_choices,default='NOC')

        name_to_be_addressed=models.CharField(max_length=100,blank=True)
        new_members_names=models.CharField(max_length=200,blank=True)
        sales_details=models.CharField(max_length=300,blank=True)
        cctv_time_from=models.DateTimeField(blank=True,default=timezone.now)
        cctv_time_to=models.DateTimeField(blank=True,default=timezone.now)
        request=models.CharField(max_length=500,blank=True)
        created=models.BooleanField(default=True)
        inprogress=models.BooleanField(default=False)
        completed=models.BooleanField(default=False)
        bank_format = models.FileField(upload_to='request_bank_format/',blank=True)


class Cheque_details(models.Model):
        entry_date=models.DateField(auto_now_add=True)
        flatno=models.CharField(max_length=5)
        user = models.CharField(max_length=50)
        cheque_date=models.DateField( auto_now_add=False)
        chequeno = models.CharField(max_length=6 , validators=[RegexValidator(r'^\d{1,10}$')])
        amount=models.IntegerField(validators=[MinValueValidator(0, message="Amount should be more than 0")])
        bank=models.CharField(max_length=200)
        remarks=models.CharField(max_length=500,default="none")
        

class LandL(models.Model):

        landl_date=models.DateField( auto_now_add=True)
        flatno=models.CharField(max_length=5)
        username=models.CharField(max_length=200)
        from_date=models.DateField( auto_now_add=False)
        to_date=models.DateField( auto_now_add=False)
        #username= models.ForeignKey(CustomUser, on_delete=models.CASCADE)
        agreement= models.FileField(upload_to='landl_docs_agreement/')
        police_ver = models.FileField(upload_to='landl_docs_police/')

member/forms.py
from django import forms 
from member.models import Request
from django.forms import ModelForm 
from datetime import date
from django.utils import timezone
from django.contrib.admin.widgets import AdminDateWidget
import time 
from member.models import Complaint
from member.models import Cheque_details,LandL
from django.forms import ModelForm

from bootstrap_datepicker_plus import DatePickerInput
from django.forms.widgets import SelectDateWidget

class RequestForm(ModelForm):

	wing_choices = [
	('A', 'A'),
	('B', 'B'),
	('C', 'C'),

	]
	wing=forms.CharField(max_length=1, widget=forms.Select(choices=wing_choices),)

	flat_choices=[
	('101','101'),
	('102','102'),
	('103','103'),
	('104','104'),
	('201','201'),
	('202','202'),
	('203','203'),
	('204','204'),
	('301','301'),
	('302','302'),
	('303','303'),
	('304','304'),
	('401','401'),
	('402','402'),
	('403','403'),
	('404','404'),
	('501','501'),
	('502','502'),
	('503','503'),
	('504','504'),
	('601','601'),
	('602','602'),
	('603','603'),
	('604','604'),
	('701','701'),
	('702','702'),
	('703','703'),
	('704','704'),
	('801','801'),
	('802','802'),
	('803','803'),
	('804','804'),
	('901','901'),
	('902','902'),
	('903','903'),
	('904','904'),

	]
	flat=forms.CharField(max_length=3,
	widget=forms.Select(choices=flat_choices),
	)

	
	cctv_time_from=forms.DateTimeField(initial=timezone.now)
	cctv_time_to=forms.DateTimeField(initial=timezone.now)
	request=forms.CharField(widget=forms.Textarea)
	created=forms.BooleanField(initial=True,required=False)
	inprogress=forms.BooleanField(initial=False,required=False)
	completed=forms.BooleanField(initial=False,required=False)
	class Meta:
		model = Request
		fields = '__all__'
		exclude=['username','date_of_issue','flatno','created','inprogress','completed']
		
	def fields_required(self, fields):
		"""Used for conditionally marking fields as required."""
		for field in fields:
			if not self.cleaned_data.get(field, ''):
				msg = forms.ValidationError("Below field is required.")
				self.add_error(field, msg)


	def clean(self):
	    choice = self.cleaned_data.get('request_type')

	    '''if choice='NOC':
	        self.fields_required(['name_to_be_addressed'])
	    else:
	        self.cleaned_data['name_to_be_addressed'] = '''

	    if choice=='AddressProof':
	    	 self.fields_required(['name_to_be_addressed'])
	    else:
	        self.cleaned_data['name_to_be_addressed'] = ''

	    if choice=='SalesAgreement':
	    	 self.fields_required(['new_members_names','sales_details','bank_format'])
	    else:
	        self.cleaned_data['new_members_names','sales_details'] = ''

	    if choice=='CCTV':
	    	 self.fields_required(['cctv_time_from','cctv_time_to'])
	    else:
	        self.cleaned_data['cctv_time_from','cctv_time_to'] = timezone.now,timezone.now

	    if choice=='Other':
	    	 self.fields_required(['request'])
	   

	    return self.cleaned_data

class ComplaintForm(ModelForm):

	wing_choices = [
	('A', 'A'),
	('B', 'B'),
	('C', 'C'),

	]
	wing=forms.CharField(max_length=1, widget=forms.Select(choices=wing_choices),)

	flat_choices=[
	('101','101'),
	('102','102'),
	('103','103'),
	('104','104'),
	('201','201'),
	('202','202'),
	('203','203'),
	('204','204'),
	('301','301'),
	('302','302'),
	('303','303'),
	('304','304'),
	('401','401'),
	('402','402'),
	('403','403'),
	('404','404'),
	('501','501'),
	('502','502'),
	('503','503'),
	('504','504'),
	('601','601'),
	('602','602'),
	('603','603'),
	('604','604'),
	('701','701'),
	('702','702'),
	('703','703'),
	('704','704'),
	('801','801'),
	('802','802'),
	('803','803'),
	('804','804'),
	('901','901'),
	('902','902'),
	('903','903'),
	('904','904'),

	]
	flat=forms.CharField(max_length=3,
	widget=forms.Select(choices=flat_choices),
	)

	class Meta:
		model = Complaint
		fields = '__all__'
		exclude=['username','flatno']



class ChequeDetailsForm(ModelForm):
	#cheque_date=forms.DateField(widget=SelectDateWidget)
	remarks=forms.CharField(widget=forms.Textarea)
	wing_choices = [
	('A', 'A'),
	('B', 'B'),
	('C', 'C'),

	]
	wing=forms.CharField(max_length=1, widget=forms.Select(choices=wing_choices),)

	
	flat_choices=[
	('101','101'),
	('102','102'),
	('103','103'),
	('104','104'),
	('201','201'),
	('202','202'),
	('203','203'),
	('204','204'),
	('301','301'),
	('302','302'),
	('303','303'),
	('304','304'),
	('401','401'),
	('402','402'),
	('403','403'),
	('404','404'),
	('501','501'),
	('502','502'),
	('503','503'),
	('504','504'),
	('601','601'),
	('602','602'),
	('603','603'),
	('604','604'),
	('701','701'),
	('702','702'),
	('703','703'),
	('704','704'),
	('801','801'),
	('802','802'),
	('803','803'),
	('804','804'),
	('901','901'),
	('902','902'),
	('903','903'),
	('904','904'),

	]
	flat=forms.CharField(max_length=3,
	widget=forms.Select(choices=flat_choices),
	)
	class Meta:
		model = Cheque_details
		fields = ['cheque_date','chequeno','amount','bank','remarks']
		exclude=['user','flatno']
		widgets={'cheque_date' : SelectDateWidget}

		#widget={'cheque_date' : DatePickerInput()}


class LandLForm(ModelForm):
	#cheque_date=forms.DateField(widget=SelectDateWidget)
	
	wing_choices = [
	('A', 'A'),
	('B', 'B'),
	('C', 'C'),

	]
	wing=forms.CharField(max_length=1, widget=forms.Select(choices=wing_choices),)

	
	flat_choices=[
	('101','101'),
	('102','102'),
	('103','103'),
	('104','104'),
	('201','201'),
	('202','202'),
	('203','203'),
	('204','204'),
	('301','301'),
	('302','302'),
	('303','303'),
	('304','304'),
	('401','401'),
	('402','402'),
	('403','403'),
	('404','404'),
	('501','501'),
	('502','502'),
	('503','503'),
	('504','504'),
	('601','601'),
	('602','602'),
	('603','603'),
	('604','604'),
	('701','701'),
	('702','702'),
	('703','703'),
	('704','704'),
	('801','801'),
	('802','802'),
	('803','803'),
	('804','804'),
	('901','901'),
	('902','902'),
	('903','903'),
	('904','904'),

	]
	flat=forms.CharField(max_length=3,
	widget=forms.Select(choices=flat_choices),
	)
	class Meta:
		model = LandL
		fields = ['from_date','to_date','agreement','police_ver']
		exclude=['username','flatno']
		widgets={'from_date' : SelectDateWidget,'to_date' : SelectDateWidget}

member/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect 
from member import forms
from . import forms
from member.tables import Cheque_details_table
from member.models import Cheque_details,Request,Complaint,LandL
from home.models import CustomUser 
from datetime import date
from django.urls import reverse
from datetime import datetime


def index(request):
	
	return render(request,'member/index.html')

def complaint(request):
	if request.method == 'POST':
		form = forms.ComplaintForm(request.POST,request.FILES)
		if form.is_valid():
			s = form.cleaned_data['wing']
			t=form.cleaned_data['flat']
			st=s+t
			record =form.save()
			record.username=request.user.username
			record.flatno=st
			record.save()
			form = forms.ComplaintForm()
		else:
			print(form.errors)
	else:
		form = forms.ComplaintForm()

	complaints = (Complaint.objects.filter(username =request.user.username )).order_by('complaint_date')

	context1={'form':form,'complaints':complaints}

	return render(request,'member/complaint.html',context1)

def request(request):
	if request.method == 'POST':
		#s=request.POST.get('wing')+request.POST.get('flat')
		#print(s)
		form = forms.RequestForm(request.POST,request.FILES)
		if form.is_valid():
			s = form.cleaned_data['wing']
			t=form.cleaned_data['flat']
			st=s+t
			record =form.save(commit=False)
			record.username=request.user.username
			record.flatno=st
			#record.date_of_issue=date.today
			record.save()
			form = forms.RequestForm()
		else:
			print(form.errors)
	else:

		form = forms.RequestForm()

	table = (Request.objects.filter(username =request.user.username )).order_by('request_date')

	context = {'form':form , 'table':table}	
	return render(request,'member/request.html',context)


def cheque_details(request):
	if request.method == 'POST':
		form = forms.ChequeDetailsForm(request.POST)
		if form.is_valid():
			print("valid")
			s = form.cleaned_data['wing']
			t=form.cleaned_data['flat']
			st=s+t
			c=form.cleaned_data['chequeno']
			a=form.cleaned_data['amount']
			b=form.cleaned_data['bank']
			rem=form.cleaned_data['remarks']
			d=form.cleaned_data['cheque_date']
			record =form.save(commit=False)			
			record.user=request.user.username
			record.flatno=st
			record.chequeno=c
			record.amount=a
			record.bank=b
			record.remarks=rem
			record.cheque_date=d
			record.save()     
			form = forms.ChequeDetailsForm()
		else:
			print(form.errors)
	else:
		form = forms.ChequeDetailsForm()

	table = Cheque_details_table(Cheque_details.objects.filter(user = request.user.username))
	context = {'form':form , 'table':table}	
	return render(request,'member/cheque_details.html',context)

def landl(request):
	if request.method == 'POST':
		form = forms.LandLForm(request.POST,request.FILES)
		if form.is_valid():
			s = form.cleaned_data['wing']
			t=form.cleaned_data['flat']
			st=s+t
			record =form.save()
			record.username=request.user.username
			record.flatno=st
			record.save()
			form = forms.LandLForm()
		else:
			print(form.errors)
	else:
		form = forms.LandLForm()
	lls = LandL.objects.filter(username = request.user.username).order_by('landl_date')
	context2 = {'form':form , 'lls':lls }	
	return render(request,'member/landl.html',context2)


def complaint_delete(request,i):

	Complaint.objects.filter(id=i).delete()

	return HttpResponseRedirect(reverse('member:complaint'))

templates/member/request.html
{%extends 'member/index.html' %}
{% block title %} complaint {% endblock %}
{% load render_table from django_tables2 %}
{% load bootstrap4 %}

{{% load static %}
{% block content %}
	<head>
	<title>Contact V15</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">


<script src="{% static 'js/request.js' %}"></script>
 <link rel="stylesheet" href="{% static 'css/request_statusbar.css' %}">
 <link rel="stylesheet" type="text/css" href="{% static 'css/request_table_style.css' %}">
 <link rel="stylesheet" type="text/css" href="{% static 'form/css/align.css' %}">
 

<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static 'form/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'form/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'form/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'form/fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'form/vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'form/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'form/vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'form/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'form/vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'form/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'form/css/main.css' %}">
<!--===============================================================================================-->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

</head>

<body >	
	<br>
	<br>
	<div class="wrap-contact100" style="margin-left: 20%;" >
			<div class="contact100-form-title" style="background-image: url({% static 'form/images/bg-01.jpg' %});">
				<span class="contact100-form-title-1">
					Request
				</span>

				<span class="contact100-form-title-2">
					Enter the details Below!
				</span>
			</div>

	<form  method="post" class="contact100-form" enctype="multipart/form-data" >
		{% csrf_token %}
		
			<div class="wrap-drop100 ">
					{% if form.wing.errors %}
						<ul class="errorlist">
    						<li style="font-size: 10px;color: red;font-style: italic;">Wing is required.</li>
						</ul>
					{% endif %}

					<span class="label-input100">Wing:</span>
					<select name="wing" id="id_wing" class="drop100" >
					<option value="" disabled selected>Wing</option>	
					<option value="A">A</option>
					<option value="B">B</option>
					<option value="C">C</option>
				</select>
			</div>

			<div class="wrap-drop100 ">
					{% if form.flat.errors %}
						<ul class="errorlist">
    						<li style="font-size: 10px;color: red;font-style: italic;">Flat no. is required.</li>
						</ul>
					{% endif %}

					<span class="label-input100">Flat no:</span>
					<select name="flat" id="id_flat" maxlength="3"  class="drop100" >
					<option value="" disabled selected>Flat No</option>	
					<option value="101">101</option>
					<option value="102">102</option>
					<option value="103">103</option>
					<option value="104">104</option>
					<option value="201">201</option>
					<option value="202">202</option>
					<option value="203">203</option>
					<option value="204">204</option>
					<option value="301">301</option>
					<option value="302">302</option>
					<option value="303">303</option>
					<option value="304">304</option>
					<option value="401">401</option>
					<option value="402">402</option>
					<option value="403">403</option>
					<option value="404">404</option>
					<option value="501">501</option>
					<option value="502">502</option>
					<option value="503">503</option>
					<option value="504">504</option>
					<option value="601">601</option>
					<option value="602">602</option>
					<option value="603">603</option>
					<option value="604">604</option>
					<option value="701">701</option>
					<option value="702">702</option>
					<option value="703">703</option>
					<option value="704">704</option>
					<option value="801">801</option>
					<option value="802">802</option>
					<option value="803">803</option>
					<option value="804">804</option>
					<option value="901">901</option>
					<option value="902">902</option>
					<option value="903">903</option>
					<option value="904">904</option>

					</select>
			</div>

			<div class="wrap-drop100 ">
					{% if form.request_type.errors %}
						<ul class="errorlist">
    						<li style="font-size: 10px;color: red;font-style: italic;">Type is required</li>
						</ul>
					{% endif %}

					<span class="label-input100">Request type:</span>
					<select id="id_request_type" class="drop100" name="request_type" >
						<option value="" disabled selected>Request type</option>	
						<option value="NOC">NOC</option>
						<option value="AddressProof">AddressProof(Passport)</option>
						<option value="SalesAgreement">SalesAgreement(NOC)</option>
						<option value="CCTV">CCTV</option>
						<option value="Other">Other</option>
					</select>
			</div>
			<div id="addressproof" class="wrap-input100 ">
				
					{% if form.name_to_be_addressed.errors %}
						<ul class="errorlist">
    						<li style="font-size: 10px;color: red;font-style: italic;">Name field is required.</li>
						</ul>
					{% endif %}

					<span class="label-input100">Name to be Addressed:</span>
					<input class="input100" type="text" id="id_name_to_be_addressed" name="name_to_be_addressed" placeholder="Enter Name">
				
			</div>

			<div id="sales" class="wrap-input100" >
				<div  class="wrap-input100 ">
					{% if form.new_members_names.errors %}
						<ul class="errorlist">
    						<li style="font-size: 10px;color: red;font-style: italic;">Members field is required.</li>
						</ul>
					{% endif %}

					<span class="label-input100">New Members Names:</span>
					<input class="input100" type="text" name="new_members_names" id="id_new_members_names" placeholder="Enter Name">
					<span class="focus-input100"></span>
				
				</div>
				<div  class="wrap-input100 ">

					{% if form.sales_details.errors %}
						<ul class="errorlist">
    						<li style="font-size: 10px;color: red;font-style: italic;"> Sales Details  field is required.</li>
						</ul>
					{% endif %}

					<span class="label-input100">Sales Details:</span>
					<input class="input100" type="text" name="sales_details" id="id_sales_details" placeholder="Enter details">
					<span class="focus-input100"></span>
				</div>

					<div class="wrap-drop100 ">

					{% if form.bank_format.errors %}
						<ul class="errorlist">
    						<li style="font-size: 10px;color: red;font-style: italic;">Bank Format Field is required.</li>
						</ul>
					{% endif %}

					<span class="label-input100">Upload Bank Format:</span>
					{{form.bank_format}}
					</div>
			</div>

				<div id="cctv">
					<div class="wrap-drop100 ">

					{% if form.cctv_time_from.errors %}
						<ul class="errorlist">
    						<li style="font-size: 10px;color: red;font-style: italic;">Time from field is required.</li>
						</ul>
					{% endif %}

					<span class="label-input100">CCTV Time From:</span>
					{{form.cctv_time_from}}
				</div>

				<div class="wrap-drop100 ">

					{% if form.to_date.errors %}
						<ul class="errorlist">
    						<li style="font-size: 10px;color: red;font-style: italic;">Time to Field is required.</li>
						</ul>
					{% endif %}

					<span class="label-input100">CCTV Time To:</span>
					{{form.cctv_time_to}}
				</div>
				</div>

			<div class="wrap-input100 ">
					{% if form.request.errors %}
						<ul class="errorlist">
    						<li style="font-size: 10px;color: red;font-style: italic;">Request is required.</li>
						</ul>
					{% endif %}

					<span class="label-input100">Request:</span>
					<textarea class="input100" name="request" placeholder="Enter Request"></textarea>
					<span class="focus-input100"></span>
			</div>

				<div class="container-contact100-form-btn">
				<input type="submit" class="contact100-form-btn" value="Submit"  style="margin-left: 80px;"/>
				</div>
				
		</form>	
</div>

<h1>Your Requests</h1>





<br>
<hr class="style-two">
<br>

{% for r in table %}
	<br>
	<div class="tablerow" id="contain" style="background-color: #ffffff;z-index: 1; position: relative;margin-left: 5%;margin-bottom: 15px;font-size: 14px;margin-left: 10%;">
	
		<div class ="flatcolumn pull-left" id="left">
			<div class=" flatno" ><span class="step">{{r.flatno}}</span></div>
		</div>

		<div class="details" id="center" style="z-index:1; position: relative;">
			<div >
		{% if r.request_type == 'SalesAgreement'%}
			
				<p class="destitle">You have made request for <b><font color=#18d26e>Sales Agreement</font></b> </p>
			<ul style="list-style-type:none">
				<li><b>New Member Names:</b>{{r.new_members_names}}</li>
				<li><b>Details:</b>{{r.sales_details}}</li>
				<li><b>Remarks:</b>{{r.request}}</li>
				<li><b>NOC Format:</b><button  class ="downloadbtn" onclick="window.location.href = '{{r.bank_format.url}}';"><i class="fa fa-download"></i>Download</button></li>

			</ul>
			
			
		{% elif r.request_type == 'AddressProof' %}
		
				<p class="destitle">You have made request for <b>Address Proof</b> </p>
			<ul style="list-style-type:none">
				<li><b>Name to be Addressed:</b>{{r.name_to_be_addressed }}</li>
				<li><b>Remarks:</b>{{r.request}}</li>
			</ul>
				
		

		{% elif r.request_type == 'CCTV' %}
		
				<p class="destitle">You have made request to view <b>CCTV Footage</b> </p>
			<ul style="list-style-type:none">
				<li><b>From:</b>{{r.cctv_time_from }}</li>
				<li><b>To:</b>{{r.cctv_time_to }}</li>
				<li><b>Remarks:</b>{{r.request}}</li>
			</ul>
				
		
		{% elif r.request_type == 'NOC' %}
		
			<p class="destitle">You have made request for <b>NOC</b> </p>
			<ul style="list-style-type:none">
				<li><b>Details:</b>{{r.request}}</li>
			</ul>
				
		
		{% else %}
		
			<p class="destitle"><b>Your request:</b>{{r.request}} </p>
				
		
		{% endif %}
		</div>
		<div >
			{% if r.completed %}
			<div class="container1" style="margin-left: 25%;">
     			 <ul class="progressbar">
          			<li class="active">Request Sent</li>
          			<li class="active">In Progress</li>
          			<li class="active">Completed</li>
          			
 				 </ul>
    		</div> 
    		
    		{% elif r.inprogress %}
			<div class="container1" style="margin-left: 25%;">
     			 <ul class="progressbar">
          			<li class="active">Request Sent</li>
          			<li class="active">In Progress</li>
          			<li>Completed</li>
          			
 				 </ul>
    		</div> 
    		
			{% else  %}
			<div class="container1" style="margin-left: 25%;">
     			 <ul class="progressbar">
          			<li class="active">Request Sent</li>
          			<li>In Progress</li>
          			<li>Completed</li>
          			
 				 </ul>
    		</div> 
    		{% endif %}
		</div>
	</div>
	
		<div class="date" id="right">
			<p class="text">Date of Issue</p>
			<i class="fa fa-calendar" aria-hidden="true"></i>
			<p>{{r.request_date }}</p>
			
		</div>
		

	</div>

</body>
{% endfor %}
{% endblock %}