commitee/urls.py
from django.contrib import admin
from django.urls import path, re_path
from commitee import views
from .views import GeneratePdf
app_name='commitee'
urlpatterns = [
	re_path(r'^$',views.index,name='index'),
	path('complaint',views.complaint,name='complaint'),
	path('request',views.request,name='request'),
	path('cheque_details',views.cheque_details,name='cheque_details'),
	path('landl',views.landl,name='landl'),
	path('option',views.option,name='option'),
	path('admin',views.admin,name='admin'),
	path('makeadmin/<str:pk>/',views.makeadmin,name="makeadmin"),
	path('makenormal/<str:pk>/',views.makenormal,name="makenormal"),
	path('psales/<int:i>/',views.sales_request_progress,name='sales_request_progress'),
	path('csales/<int:i>/',views.sales_request_complete,name='sales_request_complete'),
	path('pAddp/<int:i>/',views.Addp_request_progress,name='Addp_request_progress'),
	path('cAddp/<int:i>/',views.Addp_request_complete,name='Addp_request_complete'),
	path('pcctv/<int:i>/',views.cctv_request_progress,name='cctv_request_progress'),
	path('ccctv/<int:i>/',views.cctv_request_complete,name='cctv_request_complete'),
	path('pother/<int:i>/',views.other_request_progress,name='other_request_progress'),
	path('cother/<int:i>/',views.other_request_complete,name='other_request_complete'),
	path('pnoc/<int:i>/',views.noc_request_progress,name='noc_request_progress'),
	path('cnoc/<int:i>/',views.noc_request_complete,name='noc_request_complete'),
	path('pdfdownload', GeneratePdf.as_view(),name='htmltopdf'),
	path('announcements',views.announcements,name='announce'),
	path('announcement_delete/<int:i>/',views.announcement_delete,name='announce_delete'),
	path('visitors',views.visitorslist,name='visitors'),
	path('quotations',views.quotationslist,name='quotations'),


]

home/urls.py
from django.urls import path,re_path
from .views import SignUpView
from home import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url

urlpatterns = [
re_path(r'^$',views.base,name='base'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('visitorsform/',views.visitors, name="visitors"),
    path('quotation/',views.quotation_upload,name="quotation_upload"),
    #path('test/',views.test, name="test"),

    #path('password_reset/',auth_views.password_reset, name='password_reset'),
    #path('password_reset/done/', auth_views.password_reset_done, name='password_reset_done'),
    #re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        #auth_views.password_reset_confirm, name='password_reset_confirm'),
    #path('reset/done/', auth_views.password_reset_complete, name='password_reset_complete'),

   ]

society_website/urls.py
from django.contrib import admin
from django.urls import path, include 
from home import views,urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('member/',include('member.urls')),

    path('',views.test,name="test"),
    path('home/',include('home.urls')),
    path('home/', include('django.contrib.auth.urls')),
    path('commitee/',include('commitee.urls')),
    path('member/', views.login_success, name='login_success'),

    path('login/', views.login_success, name='login_success'),
     

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

commitee/models.py
from django.db import models

# Create your models here.

class announcement(models.Model):

	title=models.CharField(max_length=50)
	description=models.CharField(max_length=200)
	

commitee/forms.py
from django import forms
from commitee.models import announcement
from django.forms import ModelForm

class AnnounceForm(ModelForm):

	class Meta:
		model = announcement
		fields = '__all__'
		

commitee/views.py
from django.shortcuts import render
from home.models import CustomUser
from member.models import Request,Complaint
from django.http import HttpResponseRedirect  
from django.urls import reverse
from member.models import Complaint,Cheque_details,LandL

from django.db.models import Q
from django.contrib import messages
from django.http import HttpResponse
from django.views.generic import View
from society_website.utils import render_to_pdf
from commitee import forms
from commitee.models import announcement

from django.http import HttpResponse
from django.views.generic import View

from society_website.utils import render_to_pdf

from commitee import forms
from commitee.models import announcement
from home.models import visitors, Quotation

# Create your views here.

def index(request):
	
	return render(request,'commitee/c_index.html')


def complaint(request):

	intercom_complaints=Complaint.objects.filter(complaint_type='Intercom').order_by('complaint_date')
	leakage_complaints=Complaint.objects.filter(complaint_type='Leakage').order_by('complaint_date')
	cleaning_complaints=Complaint.objects.filter(complaint_type='Cleaning').order_by('complaint_date')
	other_complaints=Complaint.objects.filter(complaint_type='Other').order_by('complaint_date')


	if request.method=='POST':
		srch=request.POST['srh']
		if srch:
			match=Complaint.objects.filter(Q(flatno__icontains=srch))

			if match:
				return render(request,'commitee/c_complaint.html',{'sr':match,'intercom_complaints':intercom_complaints,'leakage_complaints':leakage_complaints,'cleaning_complaints':cleaning_complaints,'other_complaints':other_complaints})
			else:
				messages.error(request,'no result found')

				return render(request,'commitee/c_complaint.html',{'sr':match,'intercom_complaints':intercom_complaints,'leakage_complaints':leakage_complaints,'cleaning_complaints':cleaning_complaints,'other_complaints':other_complaints})
		else:
			return HttpResponseRedirect(reverse('commitee:complaint'),{'sr':match,'intercom_complaints':intercom_complaints,'leakage_complaints':leakage_complaints,'cleaning_complaints':cleaning_complaints,'other_complaints':other_complaints})	

	return render(request,'commitee/c_complaint.html',{'intercom_complaints':intercom_complaints,'leakage_complaints':leakage_complaints,'cleaning_complaints':cleaning_complaints,'other_complaints':other_complaints})

def request(request):

	sale_requests=Request.objects.filter(request_type='SalesAgreement',completed = False ).order_by('request_date')
	Addp_requests=Request.objects.filter(request_type='AddressProof',completed = False ).order_by('request_date')
	cctv_requests=Request.objects.filter(request_type='CCTV',completed = False ).order_by('request_date')
	noc_requests=Request.objects.filter(request_type='NOC',completed = False ).order_by('request_date')
	other_requests=Request.objects.filter(request_type='Other',completed = False ).order_by('request_date')
	
	if request.method=='POST':
		srch=request.POST['srh']
		if srch:
			match=Request.objects.filter(Q(flatno__icontains=srch))
			if match:
				return render(request,'commitee/c_request.html',{'sr':match,'sale_requests':sale_requests,'Addp_requests':Addp_requests,'cctv_requests':cctv_requests,'noc_requests':noc_requests,'other_requests':other_requests})
			else:
				messages.error(request,'no result found')
				return render(request,'commitee/c_request.html',{'sr':match,'sale_requests':sale_requests,'Addp_requests':Addp_requests,'cctv_requests':cctv_requests,'noc_requests':noc_requests,'other_requests':other_requests})

		else:
			return HttpResponseRedirect(reverse('commitee:request',{'sr':match,'sale_requests':sale_requests,'Addp_requests':Addp_requests,'cctv_requests':cctv_requests,'noc_requests':noc_requests,'other_requests':other_requests}))
	return render(request,'commitee/c_request.html',{'sale_requests':sale_requests,'Addp_requests':Addp_requests,'cctv_requests':cctv_requests,'noc_requests':noc_requests,'other_requests':other_requests})


def cheque_details(request):

	cheques=Cheque_details.objects.all().order_by('entry_date')
	if request.method=='POST':
		srch=request.POST['srh']
		if srch:
			match= Cheque_details.objects.filter(Q(flatno__icontains=srch))
			if match:
				return render(request,'commitee/c_cheque_details.html',{'sr':match,'cheques':cheques})
			else:
				messages.error(request,'no result found')
				return render(request,'commitee/c_cheque_details.html',{'sr':match,'cheques':cheques})

		else:
			return HttpResponseRedirect(reverse('commitee:cheque_details',{'sr':match,'cheques':cheques}))
	return render(request,'commitee/c_cheque_details.html',{'cheques':cheques})

def landl(request):
	lls=LandL.objects.all().order_by('landl_date')
	if request.method=='POST':
		srch=request.POST['srh']
		if srch:
			match= Cheque_details.objects.filter(Q(flatno__icontains=srch))
			if match:
				return render(request,'commitee/c_landl.html',{'sr':match,'lls':lls})
			else:
				messages.error(request,'no result found')
				return render(request,'commitee/c_landl.html',{'sr':match,'lls':lls})

		else:
			return HttpResponseRedirect(reverse('commitee:landl',{'sr':match,'lls':lls}))


	return render(request,'commitee/c_landl.html',{'lls':lls})


def option(request):

	return render(request,'commitee/option.html')

def admin(request):
	mem=CustomUser.objects.all()
	return render(request,'commitee/admin.html',{'mem':mem})

def makeadmin(request, pk):
    r = CustomUser.objects.get(pk=pk)
    r.rights="commitee"
    r.save()
    return HttpResponseRedirect(reverse('commitee:admin'))

def makenormal(request, pk):
    r = CustomUser.objects.get(pk=pk)
    r.rights="normal"
    r.save()
    return HttpResponseRedirect(reverse('commitee:admin'))
	
def sales_request_progress(request,i):

	Request.objects.filter(id=i).update(inprogress=True)

	return HttpResponseRedirect(reverse('commitee:request'))
	#return render(request,'commitee/c_request.html')

def sales_request_complete(request,i):

	Request.objects.filter(id=i).update(completed=True)

	return HttpResponseRedirect(reverse('commitee:request'))

def Addp_request_progress(request,i):

	Request.objects.filter(id=i).update(inprogress=True)

	return HttpResponseRedirect(reverse('commitee:request'))
	#return render(request,'commitee/c_request.html')

def Addp_request_complete(request,i):

	Request.objects.filter(id=i).update(completed=True)

	return HttpResponseRedirect(reverse('commitee:request'))

def cctv_request_progress(request,i):

	Request.objects.filter(id=i).update(inprogress=True)

	return HttpResponseRedirect(reverse('commitee:request'))
	#return render(request,'commitee/c_request.html')

def cctv_request_complete(request,i):

	Request.objects.filter(id=i).update(completed=True)

	return HttpResponseRedirect(reverse('commitee:request'))

def noc_request_progress(request,i):

	Request.objects.filter(id=i).update(inprogress=True)

	return HttpResponseRedirect(reverse('commitee:request'))
	#return render(request,'commitee/c_request.html')

def noc_request_complete(request,i):

	Request.objects.filter(id=i).update(completed=True)

	return HttpResponseRedirect(reverse('commitee:request'))
def other_request_progress(request,i):

	Request.objects.filter(id=i).update(inprogress=True)

	return HttpResponseRedirect(reverse('commitee:request'))
	#return render(request,'commitee/c_request.html')

def other_request_complete(request,i):

	Request.objects.filter(id=i).update(completed=True)

	return HttpResponseRedirect(reverse('commitee:request'))



class GeneratePdf(View):
	def get(self, request, *args, **kwargs):
		cheques=Cheque_details.objects.all().order_by('entry_date')
		pdf = render_to_pdf('commitee/chequetopdf.html',{'cheques':cheques})
		return HttpResponse(pdf, content_type='application/pdf')



def announcements(request):

	if request.method == 'POST':
		form = forms.AnnounceForm(request.POST)
		if form.is_valid():
			form.save()
			form = forms.AnnounceForm()
	else:
		form = forms.AnnounceForm()

	an=announcement.objects.all()

	return render(request,'commitee/c_announcements.html',{'form':form,'an':an})

def announcement_delete(request,i):

	announcement.objects.filter(id=i).delete()

	return HttpResponseRedirect(reverse('commitee:announce'))

def visitorslist(request):
	v=visitors.objects.all()
	return render(request,'commitee/visitors.html',{'v':v})

def quotationslist(request):
	q=Quotation.objects.all()
	return render(request,'commitee/quotations.html',{'q':q})

templates/commitee/admin.html
<!DOCTYPE html>
	<html>
	<head>
		<title>	admin</title>
		<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <style >
  	.btn:active{
  		background-color: green;
  	}
 		.btn:focus{
  		background-color: grey;
  	}
  </style>

  <a href="/" class="btn btn-danger" style="float: right; font-size:15px; vertical-align:middle; margin-bottom: 10px; margin-right: 10px;margin-top: 10px;">Log Out</a>
	</head>


	<body>
	
	
<div class="container" style="padding-top: 4%;">
<table class="table">
<tr class>
	<th>UserName</th>
	<th>Flat No</th>
	<th>Email</th>
	<th></th>
	<th></th>
</tr>
	{% for m in mem %}
<tr class>
	<td>{{ m.username }}</td>
	<td>{{ m.flatno }}</td>
	<td>{{ m.email }}</td>
	<td><a href="{% url 'commitee:makeadmin' m.username %}" class="btn btn-success" type="button" style="border-radius: 25px;">Commitee</a></td>
	<td><a href="{% url 'commitee:makenormal' m.username %}"class="btn btn-success" type="button" style="border-radius: 25px;">Normal</a></td>
</tr>
	{% endfor %}

</table>
</div>
</body>



</html>	

templates/commitee/c_announcements.html
{% extends 'commitee/c_index.html' %}

	{% block content %}
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>


	<div class="jumbotron" style="padding-top: 2%">
<form method="POST" style="text-align: center;" >


{% csrf_token %}
  {{ form.as_table }}

  <input type="submit" value="Submit" class="btn btn-primary" style="border-radius: 25px;">
</form>
</div>

</form>
<div class="container">
<h2>Present Announements</h2>

<table class="table">
	<tr class="danger">
		<th>Title</th>
		<th>Description</th>
		<th>Delete</th>
	</tr>
	{% for a in an %}
	<tr class="info">
		<td>{{a.title}}</td>
		<td>{{a.description}}</td>
		<td><a href="{% url 'commitee:announce_delete' a.id %}" class="btn btn-success">Delete</a></td>
	</tr>
	{% endfor %}
</table>
</div>
{% endblock %}

templates/commitee/c_cheque_details.html
{% extends 'commitee/c_index.html' %}

{% block content %}

<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

<div class="jumbotron" style="padding-top:2%;align-items: center;">
<form method="post" style="text-align: center;">
{% csrf_token %}
<input type="text" name="srh" placeholder="Enter Flat No.">
<button type="submit" class="btn btn-primary" style="border-radius: 25px">Search</button>
{% if messages %}
		{% for k in messages %}
			{{ k }}
		{% endfor %}
	{% endif %}
</form>

</div>

<div class="container">
	<table class="table">
	{% if sr %}
		
	<tr class="danger">
		<th>Date of entry</th>
	<th>Flat No</th>
	<th>Cheque Date</th>z
	<th>Cheque Number</th>
	<th>Amount</th>
	<th>Bank Name</th>
	<th>Remarks</th>

	</tr>
	{% for k in sr %}
	<tr class="success">
		<td>{{k.entry_date }}</td>
		<td>{{k.flatno}}</td>
		<td>{{k.cheque_date}}</td>
		<td>
			{{k.chequeno }}
		</td>
		<td>{{ k.amount }}</td>
	<td>{{ k.bank }}</td>
	<td>{{ k.remarks }}</td>

	{% endfor %}
	{% endif %}
		
	</tr>
		</table>
	
</div>



<hr>

<div class="container">
<h2>Cheque Details</h2>

<table class="table table-striped">
	
	<tr>
	<th>Date of entry</th>
	<th>Flat No</th>
	<th>Cheque Date</th>z
	<th>Cheque Number</th>
	<th>Amount</th>
	<th>Bank Name</th>
	<th>Remarks</th>
</tr>

	{% for ch in cheques %}
<tr>
	<td>{{ ch.entry_date }}</td>
	<td>{{ ch.flatno }}</td>
	<td>{{ ch.cheque_date }}</td>
	<td>{{ ch.chequeno }}</td>
	<td>{{ ch.amount }}</td>
	<td>{{ ch.bank }}</td>
	<td>{{ ch.remarks }}</td>

</tr>	
	{% endfor %}

</table>
</div>
<hr>

<a href="{% url 'commitee:htmltopdf' %}" class="btn btn-primary" style="border-radius: 25px;">download pdf </a>
{% endblock %}

templates/commitee/c_index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %} Commitee page {% endblock %}</title>
	<link rel="stylesheet" href="{% static 'css/member_home.css' %}">
	 <link rel="stylesheet" href="{% static 'css/style.css' %}"> 
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">  
</head>


<body style="margin:0px;background-color: #eee;">

<div class="pull-left" style="z-index: 200;position: absolute;margin-left: 10px;">
        <h4><font color="white" style="text-transform: uppercase;">Valentine Apts</font></h4>    
      </div>
  
  <header  style="background: rgba(0, 0, 0, 0.9);overflow:hidden;">
    
      <nav id="nav-menu-container"  style="margin-top:20px;">
        <ul class="nav-menu">
          
          <li><a href="/">Home</a></li>
          <li><a href="{% url 'login' %}">Logout</a></li>
         
        </ul>
      </nav>
   
  </header> 

<div class="sidenav" style="padding-top:80px;">
	
	<a href="{% url 'commitee:complaint' %}">Complaint</a>
	<a href="{% url 'commitee:request' %}">Request</a>
	<a href="{% url 'commitee:cheque_details' %}">Cheque Details</a>
	<a href="{% url 'commitee:landl' %}">Leave & License</a>
	<a href="{% url 'commitee:announce' %}">Add Announcement</a>
	<a href="{% url 'commitee:visitors' %}"> Visitors list</a>
	<a href="{% url 'commitee:quotations' %}"> Quotation list</a>


</div>
<div id="content" name="content" class ="main">
	{% block content %}
	{% endblock %}
</div>
</body>
</html>

templates/commitee/c_request.html
{% extends 'commitee/c_index.html' %}

	{% block content %}

 <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

<div class="jumbotron" style="padding-top:2%">
<form method="post" style="text-align: center;">
{% csrf_token %}
<input type="text" name="srh" placeholder="Enter Flat No.">
<button type="submit" class="btn btn-primary" style="border-radius: 25px;">Search</button>

{% if messages %}
		{% for k in messages %}
			{{ k }}
		{% endfor %}
	{% endif %}
</form>

</div>


<div class="container">
	<table class="table">
	{% if sr %}
		
	<tr class="danger">
		<th>Date Of Issue</th>
		<th>Flat No</th>
		<th>Request Type</th>
		<th>Request</th>

	</tr>
	{% for k in sr %}
	<tr class="success">
		<td>{{k.request_date }}</td>
		<td>{{k.flatno}}</td>
		<td>{{k.request_type}}</td>
		<td>
			{{k.request }}
		</td>
	{% endfor %}
	{% endif %}
		
	</tr>
		</table>
	
</div>

<hr>

<div class="container">
<h2>Sales Agreement (NOC)</h2>
<table class="table table-striped">
	<tr>
		<th>Date Of Issue</th>
		<th>Flat No</th>
		<th>New Member Names</th>
		<th>Sales Details</th>
		<th>Bank Format</th>
		<th>Remarks</th>
		<th>Update Progress</th>
		<th>Update Completed</th>

	</tr>
	{% for r in sale_requests %}
	<tr>
		<td>{{ r.request_date }}</td>
		<td>{{r.flatno}}</td>
		<td>{{r.new_members_names}}</td>
		<td>{{r.sales_details}}</td>
		<td><a href="{{r.bank_format.url}}" class="btn btn-success btn-sm" target="_blank">Download</a></td>
		<td>{{r.request}}</td>
		<td><a href="{% url 'commitee:sales_request_progress' r.id %}" class="btn btn-success btn-sm" >Click</a></td>
		<td><a href="{% url 'commitee:sales_request_complete' r.id %}" class="btn btn-success btn-sm" >Click</a></td>

	</tr>

	{% endfor %}

</table>
</div>

<div class="container">

<h2>Address Proof for Passport </h2>


<table class="table table-striped">
	<tr>
		<th>Date Of Issue</th>
		<th>Flat No</th>
		<th>Name to be Addressed</th>
		<th>Remarks</th>
		<th>Update Progress</th>
		<th>Update Completed</th>

	</tr>
	{% for r in Addp_requests %}
	<tr>
		<td>{{ r.request_date }}</td>
		<td>{{r.flatno}}</td>
		<td>{{r.name_to_be_addressed}}</td>
		<td>{{r.request}}</td>
		<td><a href="{% url 'commitee:Addp_request_progress' r.id %}" class="btn btn-success btn-sm" > Click</a></td>
		<td><a href="{% url 'commitee:Addp_request_complete' r.id %}" class="btn btn-success btn-sm" >Click</a></td>

	</tr>

	{% endfor %}

</table>
</div>
<div class="container">

<h2>CCTV Request</h2>

<table class="table table-striped">
	<tr>
		<th>Date Of Issue</th>
		<th>Flat No</th>
		<th>From</th>
		<th>To</th>
		<th>Remarks</th>
		<th>Update Progress</th>
		<th>Update Completed</th>

	</tr>
	{% for r in cctv_requests %}
	<tr>
		<td>{{ r.request_date }}</td>
		<td>{{r.flatno}}</td>
		<td>{{r.cctv_time_from}}</td>
		<td>{{r.cctv_time_to}}</td>
		<td>{{r.request}}</td>
		<td><a href="{% url 'commitee:cctv_request_progress' r.id %}" class="btn btn-success btn-sm" >Click</a></td>
		<td><a href="{% url 'commitee:cctv_request_complete' r.id %}" class="btn btn-success btn-sm" >Click</a></td>

	</tr>

	{% endfor %}

</table>
</div>
<div class="container">

<h2>NOC</h2>

<table class="table table-striped">
	<tr>
		<th>Date Of Issue</th>
		<th>Flat No</th>
		<th>Remarks</th>
		<th>Update Progress</th>
		<th>Update Completed</th>

	</tr>
	{% for r in noc_requests %}
	<tr>
		<td>{{ r.request_date }}</td>
		<td>{{r.flatno}}</td>
		<td>{{r.request}}</td>
		<td><a href="{% url 'commitee:noc_request_progress' r.id %}" class="btn btn-success btn-sm" >Click</a></td>
		<td><a href="{% url 'commitee:noc_request_complete' r.id %}" class="btn btn-success btn-sm" >Click</a></td>

	</tr>

	{% endfor %}

</table>

</div>
<div class="container">
<h1>Other </h1>

<table class="table table-striped">
	<tr>
		<th>Date Of Issue</th>
		<th>Flat No</th>
		<th>Remarks</th>
		<th>Update Progress</th>
		<th>Update Completed</th>

	</tr>
	{% for r in other_requests %}
	<tr>
		<td>{{ r.request_date }}</td>
		<td>{{r.flatno}}</td>		
		<td>{{r.request}}</td>
		<td><a href="{% url 'commitee:other_request_progress' r.id %}" class="btn btn-success btn-sm" >Click</a></td>
		<td><a href="{% url 'commitee:other_request_complete' r.id %}" class="btn btn-success btn-sm" >Click</a></td>

	</tr>

	{% endfor %}

</table>
</div>

	{% endblock %}

templates/commitee/chequetopdf.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

	<h1 align="center">Valentine Apt III</h1><h3 align="right">Date:&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</h3>
	<h3>Branch :Dindoshi </h3>
	<h3>Account No :123456789</h3>

<table>	
	<tr>
	<th>Date of entry</th>
	<th>Flat No</th>
	<th>Cheque Date</th>z
	<th>Cheque Number</th>
	<th>Amount</th>
	<th>Bank Name</th>
	<th>Remarks</th>
</tr>

	{% for ch in cheques %}
<tr>
	<td>{{ ch.entry_date }}</td>
	<td>{{ ch.flatno }}</td>
	<td>{{ ch.cheque_date }}</td>
	<td>{{ ch.chequeno }}</td>
	<td>{{ ch.amount }}</td>
	<td>{{ ch.bank }}</td>
	<td>{{ ch.remarks }}</td>

</tr>	
	{% endfor %}

</table>

</body>
</html>

templates/commitee/visitors.html
{% extends 'commitee/c_index.html' %}

	{% block content %}
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>


  <div class="container">
<h2>Visitors</h2>

<table class="table table-striped">
	<tr class>
		<th>Name</th>
		<th>telephone Number</th>
		<th>Flat No</th>
		<th> Purpose</th>
	</tr>
	{% for a in v %}
	<tr class=>
		<td>{{a.name}}</td>
		<td>{{a.telephone}}</td>
		<td>{{a.flat_no}}</td>
		<td>{{a.purpose}}</td>
		
	</tr>
	{% endfor %}
</table>
</div>
{% endblock %}